# Generated by Django 5.2.3 on 2025-06-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_image_remove_post_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post_images/i.webp', upload_to='post_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='profession',
            field=models.CharField(default='post_images/i.webp', max_length=255),
            preserve_default=False,
        ),
    ]
