# Generated by Django 5.2.3 on 2025-06-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_image_post_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
